# Generated by Django 4.0.4 on 2022-05-02 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StopConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=2, help_text='Travel time in minutes')),
                ('stop1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='routes.stop')),
                ('stop2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='routes.stop')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_on_route', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.stop')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(through='routes.RouteStops', to='routes.stop'),
        ),
    ]
