# Generated by Django 4.0.4 on 2022-05-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_stop_slug_alter_route_number_alter_stop_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RouteStops',
            new_name='RouteStop',
        ),
    ]
