# Generated by Django 4.0.4 on 2022-05-20 10:59

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.TramUserManager()),
            ],
        ),
    ]
