# Generated by Django 4.0.4 on 2022-05-26 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity_time', models.IntegerField(choices=[(15, 'Ticket 15 Min'), (30, 'Ticket 30 Min'), (60, 'Ticket 1 Hour'), (1440, 'Ticket 1 Day'), (10080, 'Ticket 1 Week'), (43200, 'Ticket 1 Month')])),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
